# .circleci/config.yml
version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  deploy:
    working_directory: ~/yoone
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: deploy
          command: npm run deploy

workflows:
  version: 2
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
